### ISSUE TITLE
Use an Arabic font

### ISSUE THREAD

**Issue by Fcmam5** [reactjs/ar.reactjs.org#100]
As Salam Alikom, Hello everyone :)

I suggest setting an "Arabic-friendly" and a more font.

In my case the fonts look like this (Firefox on Ubuntu, using the default fonts):

![Screenshot from 2019-06-12 19-36-26](https://user-images.githubusercontent.com/9090674/59373498-1a4f1f00-8d4a-11e9-8bc6-79b5df33c419.png)

And for me, it looks a bit ugly.
I suggest setting a better font. If that's possible, what font should we use?

**Comment by 22mahmoud** [comment]
I like cairo font

**Comment by 3imed-jaberi** [comment]
You can choose between these fonts : 
https://fonts.google.com/?subset=arabic
I like Changa font 😄 ..

**Comment by maskeddeveloper** [comment]
> I like cairo font

Yes Cairo font is the best

**Comment by mohshbool** [comment]
I like the Geeza Pro font, couldn't find it on Google Fonts though

**Comment by 3imed-jaberi** [comment]
I think it is worth discussing this subject through SLACK ..
So, no need to keep this issue open ..
