### ISSUE TITLE
setup algolia docsearch for ar.reactjs.org and use arabic widget

### ISSUE THREAD

**Issue by Fcmam5** [reactjs/ar.reactjs.org#106]
We should setup a proper algolia application for [ar.reactjs.org](ar.reactjs.org) with a widget in Arabic.

https://github.com/reactjs/ar.reactjs.org/blob/8c6b8d497a6bc2eda3b2c5b9862c8cfc2b7e383a/src/components/LayoutHeader/DocSearch.js#L26

**Comment by iRayan7** [comment]
@tesseralis

**Comment by tesseralis** [comment]
Sure! to do this you need to change the [DocSearch API key](https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25)

 One of the maintainers needs to [sign up for DocSearch here](https://community.algolia.com/docsearch/#join-docsearch-program)

I don't know how the Arabic widget works but the Algolia person is usually pretty helpful.

**Comment by Fcmam5** [comment]
I got the API key for it, I'm gonna submit a PR :)
