### ISSUE TITLE
Correct translation of the word "Docs"

### ISSUE THREAD

**Issue by Fcmam5** [reactjs/ar.reactjs.org#130]
`Docs` word is translated as `المستندات`, I think that it should be `التوثيق`.
What do you think?

PS: It's also translated as توثيق in [Arabeyes dictionary](https://www.arabeyes.org/techdict:Documentation).

![Screenshot from 2019-07-06 02-09-29](https://user-images.githubusercontent.com/9090674/60748995-020ea080-9f94-11e9-98e5-ed92aff887b5.png)

**Comment by 3imed-jaberi** [comment]
@Fcmam5 , thanks bro for your issue  but there is already a ISSUE #122 to discuss all changes in the terminology used.
