### ISSUE TITLE
Add DocSearch

### ISSUE THREAD

**Issue by tesseralis** [reactjs/ar.reactjs.org#153]
Congrats on almost finishing the core Arabic translation! One of the final steps is to change the [DocSearch API key](https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25). One of the maintainers needs to [sign up for DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program) in order to do this.

**Comment by Fcmam5** [comment]
Hi @tesseralis, we already did that in #128
