### ISSUE TITLE
Must sync with reactjs.org

### ISSUE THREAD

**Issue by Fcmam5** [reactjs/ar.reactjs.org#192]
Hello everyone,
Please notice that there are *many* pending PRs by @reactjs-translation-bot!
We must review, check the merge conflicts and retranslate what needs to be translated again, not only approving the PR!

Pending branches:
- [x] #170 -> @Fcmam5 
- [x] #172 -> @Fcmam5 
- [ ] #173 -> @Fcmam5 
- [ ] #186 -> @3imed-jaberi 
- [ ] #187 
- [ ] #188 
- [ ] #189 -> @3imed-jaberi 
- [ ] #190 
- [ ] #196 -> @3imed-jaberi

**Comment by mohamedsgap** [comment]
Hi @Fcmam5 , I really want to help and contribute in the translation!

**Comment by Fcmam5** [comment]
> Hi @Fcmam5 , I really want to help and contribute in the translation!

Sure Mohamed! You are more than welcome :smiley: . You can start by revewing the pending PRs with us, or by fixing typos in the translated pages or (and pleaaase help me out with #163 :sob: If you want to, we can close this PR and you start fresh by working on a new one)
