### ISSUE TITLE
Dealing with RTL 

### ISSUE THREAD

**Issue by fawzisf** [reactjs/ar.reactjs.org#5]
we need to discuss if we need to add RTL support to the docs website.

**Comment by asantarissy** [comment]
Hello @fawzisf I agree with you, I think we should start working on the RTL before we start translating anything, I did a quick scan on pages and components and I think I have a solution for it, I'll create a PR today for sure.

**Comment by iRayan7** [comment]
Hi guys,
I think we should focus on the translation first, since this is a concern we share with the translators of Hebrew and Persia languages.
Also at the slack group we have a channel for rtl with the translators of those languages, you should discuss it there with them 👍

**Comment by asantarissy** [comment]
Thanks @iRayan7 and yes I agree with you, but it's way better for us to translate pages and see what we're doing as a final result.

Please check my PR #8 I tried to cover all pages and components, please check it out and let me know your thoughts.

Cheers 😄

**Comment by Emmanuel-Melon** [comment]
> Hi guys,
> I think we should focus on the translation first since this is a concern we share with the translators of Hebrew and Persian languages.
> Also at the slack group, we have a channel for rtl with the translators of those languages, you should discuss it there with them 👍

Link to the slack channel please

**Comment by asantarissy** [comment]
> > Hi guys,
> > I think we should focus on the translation first since this is a concern we share with the translators of Hebrew and Persian languages.
> > Also at the slack group, we have a channel for rtl with the translators of those languages, you should discuss it there with them 👍
> 
> Link to the slack channel please

Here you go: [Slack Channel](https://github.com/orgs/reactjs/teams/reactjs-org-arabic-translation/discussions/1)
